name: create-release
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get manifest version
        id: manifest
        shell: pwsh
        run: |
          $manifest = Get-Content -Raw -path Thunderstore/manifest.json
          $manifest -match '"version_number":.*"([.\d\w-+]+)"'
          echo "VERSION=$($matches[1])" >> $env:GITHUB_OUTPUT

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build project
        id: build
        shell: pwsh
        run: |
          cd src
          $destination = dotnet build --configuration Release
          "$($destination)" -match '"([^"\n\r\t]+\.zip)"'
          echo "DESTINATION=$($matches[1])" >> $env:GITHUB_OUTPUT
          $matches[1] -match '\\*([^\\\n\r\t]+).zip'
          echo "NAME=$($matches[1])" >> $env:GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.DESTINATION }}
          name: ${{ steps.build.outputs.NAME}}-${{ steps.manifest.outputs.VERSION }}.zip
